import type {
  WorkflowLinkDefinition,
  WorkflowNodeDefinition,
} from "@/components/ai-chat/ai-workflow-canvas";

export const authoringNodes: WorkflowNodeDefinition[] = [
  {
    id: "brief",
    category: "Input",
    title: "Release brief",
    description: "Collect scope, constraints, and the target release window.",
    kind: "input",
    status: "completed",
    progress: 100,
    owner: "Product lead",
    position: { x: 0, y: 120 },
    handles: { target: false, source: true },
    tasks: [
      { label: "Capture release goal", status: "completed" },
      { label: "Attach acceptance criteria", status: "completed" },
    ],
  },
  {
    id: "research",
    category: "Agent",
    title: "Research dependencies",
    description:
      "Map affected packages, routes, and compatibility constraints.",
    kind: "agent",
    status: "waiting",
    progress: 0,
    agent: "Research agent",
    position: { x: 340, y: 120 },
    handles: { target: true, source: true },
    tasks: [
      { label: "Inspect repository map", status: "waiting" },
      { label: "Check package contracts", status: "waiting" },
    ],
  },
  {
    id: "decision",
    category: "Routing",
    title: "Risk decision",
    description: "Choose the standard or guarded implementation path.",
    kind: "branch",
    status: "waiting",
    progress: 0,
    owner: "Workflow router",
    position: { x: 680, y: 120 },
    handles: { target: true, source: true },
  },
  {
    id: "implement",
    category: "Code",
    title: "Implement changes",
    description: "Apply the approved plan using existing repository patterns.",
    kind: "code",
    status: "waiting",
    progress: 0,
    agent: "Implementation agent",
    position: { x: 1020, y: 20 },
    handles: { target: true, source: true },
    tasks: [
      { label: "Update shared primitives", status: "waiting" },
      { label: "Add route integration", status: "waiting" },
    ],
  },
  {
    id: "approval",
    category: "Checkpoint",
    title: "Human approval",
    description: "Pause risky migrations for explicit reviewer confirmation.",
    kind: "approval",
    status: "waiting",
    progress: 0,
    owner: "Release owner",
    position: { x: 1020, y: 250 },
    handles: { target: true, source: true },
  },
  {
    id: "verify",
    category: "Quality",
    title: "Verify and publish",
    description: "Run focused checks, summarize evidence, and prepare release.",
    kind: "review",
    status: "waiting",
    progress: 0,
    agent: "Verification agent",
    position: { x: 1370, y: 120 },
    handles: { target: true, source: false },
    tasks: [
      { label: "Run targeted tests", status: "waiting" },
      { label: "Prepare release summary", status: "waiting" },
    ],
  },
];

export const authoringLinks: WorkflowLinkDefinition[] = [
  { id: "brief-research", source: "brief", target: "research" },
  { id: "research-decision", source: "research", target: "decision" },
  {
    id: "decision-implement",
    source: "decision",
    target: "implement",
    label: "STANDARD",
  },
  {
    id: "decision-approval",
    source: "decision",
    target: "approval",
    kind: "conditional",
    label: "HIGH RISK",
  },
  { id: "approval-verify", source: "approval", target: "verify" },
  { id: "implement-verify", source: "implement", target: "verify" },
];

export const liveBaseNodes: WorkflowNodeDefinition[] = [
  {
    id: "context",
    category: "Context",
    title: "Read project context",
    description: "Resolve the requested change against the current repository.",
    kind: "input",
    status: "completed",
    progress: 100,
    duration: "1.2s",
    agent: "Codex",
    file: "AGENTS.md",
    tool: "read",
    position: { x: 0, y: 130 },
    handles: { target: false, source: true },
  },
  {
    id: "map",
    category: "Research",
    title: "Map affected surfaces",
    description:
      "Inspect routes, components, and their nearest design patterns.",
    kind: "agent",
    status: "completed",
    progress: 100,
    duration: "3.8s",
    agent: "Codex",
    file: "src/components/ai-chat",
    tool: "search",
    position: { x: 340, y: 130 },
    handles: { target: true, source: true },
  },
  {
    id: "build",
    category: "Implementation",
    title: "Build workflow primitives",
    description:
      "Compose repository-native canvas, node, edge, and panel blocks.",
    kind: "code",
    status: "running",
    progress: 58,
    duration: "00:18",
    agent: "Codex",
    file: "src/components/ai-elements/node.tsx",
    tool: "apply_patch",
    position: { x: 680, y: 130 },
    handles: { target: true, source: true },
    tasks: [
      { label: "Create canvas primitives", status: "completed" },
      { label: "Compose execution nodes", status: "running" },
      { label: "Wire responsive inspector", status: "waiting" },
    ],
  },
  {
    id: "tests",
    category: "Verification",
    title: "Run focused checks",
    description: "Validate behavior, responsiveness, and typed integrations.",
    kind: "tool",
    status: "waiting",
    progress: 0,
    agent: "Verification agent",
    position: { x: 1020, y: 30 },
    handles: { target: true, source: true },
    tasks: [
      { label: "Lint changed files", status: "waiting" },
      { label: "Exercise interactions", status: "waiting" },
    ],
  },
  {
    id: "review",
    category: "Review",
    title: "Visual quality review",
    description:
      "Inspect spacing, edge alignment, themes, and mobile behavior.",
    kind: "review",
    status: "waiting",
    progress: 0,
    owner: "Design reviewer",
    position: { x: 1020, y: 260 },
    handles: { target: true, source: true },
  },
  {
    id: "complete",
    category: "Output",
    title: "Publish evidence",
    description: "Summarize changes and attach validation evidence to the run.",
    kind: "approval",
    status: "waiting",
    progress: 0,
    owner: "Release owner",
    position: { x: 1370, y: 130 },
    handles: { target: true, source: false },
  },
];

export const liveLinks: WorkflowLinkDefinition[] = [
  { id: "context-map", source: "context", target: "map" },
  { id: "map-build", source: "map", target: "build", kind: "active" },
  { id: "build-tests", source: "build", target: "tests", kind: "conditional" },
  {
    id: "build-review",
    source: "build",
    target: "review",
    kind: "conditional",
  },
  { id: "tests-complete", source: "tests", target: "complete" },
  { id: "review-complete", source: "review", target: "complete" },
];

export const reviewNodes: WorkflowNodeDefinition[] = [
  {
    id: "planner",
    category: "Planning agent",
    title: "Plan release migration",
    description:
      "Break the request into verifiable workstreams and checkpoints.",
    kind: "agent",
    status: "completed",
    progress: 100,
    duration: "4.1s",
    agent: "Planner",
    position: { x: 0, y: 180 },
    handles: { target: false, source: true },
    tasks: [
      { label: "Map requirements", status: "completed" },
      { label: "Assign workstreams", status: "completed" },
    ],
  },
  {
    id: "researcher",
    category: "Research agent",
    title: "Audit dependencies",
    description: "Verify package contracts and migration risks independently.",
    kind: "agent",
    status: "completed",
    progress: 100,
    duration: "8.7s",
    agent: "Researcher",
    file: "package.json",
    tool: "search",
    position: { x: 350, y: 30 },
    handles: { target: true, source: true },
  },
  {
    id: "implementer",
    category: "Implementation agent",
    title: "Apply migration",
    description: "Implement the scoped changes and record touched surfaces.",
    kind: "code",
    status: "revised",
    progress: 100,
    duration: "42.6s",
    agent: "Implementer",
    file: "src/lib/runtime-adapter.ts",
    tool: "apply_patch",
    position: { x: 350, y: 330 },
    handles: { target: true, source: true },
    tasks: [
      { label: "Apply initial change", status: "completed" },
      { label: "Reopen adapter after review", status: "completed" },
    ],
  },
  {
    id: "tester",
    category: "Verification agent",
    title: "Verify contracts",
    description: "Run focused checks against both parallel workstreams.",
    kind: "tool",
    status: "completed",
    progress: 100,
    duration: "18.3s",
    agent: "Tester",
    tool: "pnpm test",
    position: { x: 720, y: 30 },
    handles: { target: true, source: true },
  },
  {
    id: "reviewer",
    category: "Review agent",
    title: "Review changed surfaces",
    description:
      "Compare declared scope with observed files and request one revision.",
    kind: "review",
    status: "completed",
    progress: 100,
    duration: "11.8s",
    agent: "Reviewer",
    file: "src/lib/runtime-adapter.ts",
    tool: "diff",
    position: { x: 720, y: 330 },
    handles: { target: true, source: true },
  },
  {
    id: "approval",
    category: "Human checkpoint",
    title: "Approve release",
    description: "Review evidence from every agent before publishing the run.",
    kind: "approval",
    status: "completed",
    progress: 100,
    duration: "2m 14s",
    owner: "Rakesh",
    position: { x: 1090, y: 180 },
    handles: { target: true, source: true },
  },
  {
    id: "published",
    category: "Run output",
    title: "Release ready",
    description:
      "All required evidence is attached and the guarded path completed.",
    kind: "review",
    status: "completed",
    progress: 100,
    duration: "3m 39s",
    owner: "Workflow system",
    position: { x: 1450, y: 180 },
    handles: { target: true, source: false },
  },
];

export const reviewLinks: WorkflowLinkDefinition[] = [
  { id: "planner-researcher", source: "planner", target: "researcher" },
  { id: "planner-implementer", source: "planner", target: "implementer" },
  { id: "researcher-tester", source: "researcher", target: "tester" },
  {
    id: "implementer-reviewer",
    source: "implementer",
    target: "reviewer",
    kind: "active",
  },
  { id: "tester-approval", source: "tester", target: "approval" },
  { id: "reviewer-approval", source: "reviewer", target: "approval" },
  { id: "approval-published", source: "approval", target: "published" },
  {
    id: "reviewer-implementer",
    source: "reviewer",
    target: "implementer",
    kind: "conditional",
    label: "REVISION",
  },
];
